# Generated by Django 2.2.7 on 2019-11-24 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(default='Hyper X', max_length=20, verbose_name='Marca Memória')),
                ('capacidade', models.CharField(choices=[('4', '4'), ('8', '8'), ('16', '16'), ('32', '32'), ('64', '64')], max_length=20, verbose_name='Capacidade')),
            ],
        ),
        migrations.CreateModel(
            name='Processador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('intel_core_i5', 'Intel Core i5'), ('intel_core_i7', 'Intel Core i7'), ('amd_atlhon', 'AMD Athlon'), ('amd_rysen7', 'AMD Rysen 7')], max_length=20, verbose_name='Nome')),
                ('marca', models.CharField(max_length=20, verbose_name='Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Vga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(choices=[('gigabyte_geforce_gtx_1060_6gb', 'Gigabyte Geforce GTX 1060 6GB'), ('pny_rtx_2060_6gb', 'PNY RTX 2060 6GB'), ('radeon_rx_580_8GB', 'Radeon RX 580 8GB')], max_length=20, verbose_name='Modelo')),
            ],
        ),
        migrations.CreateModel(
            name='PlacaMae',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('asus_prime', 'Asus Prime'), ('gigabyte', 'Gigabyte'), ('asrock_fatal', 'AsRock Fatal')], max_length=20, verbose_name='Nome Placa Mãe')),
                ('slots', models.CharField(choices=[('2', '2'), ('4', '4')], max_length=20, verbose_name='Slots Placa Mãe')),
                ('total_ram', models.CharField(max_length=20, verbose_name='Memória Total')),
                ('video', models.BooleanField(default=False, verbose_name='Vídeo Integrado')),
                ('processador_socket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.Processador')),
            ],
        ),
    ]
