# Generated by Django 2.2.7 on 2019-11-24 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pedidos', '0002_auto_20191124_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compatibilidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processador_c', models.BooleanField(default=False)),
                ('memoria_c', models.BooleanField(default=False)),
                ('placa_mae_c', models.BooleanField(default=False)),
                ('vga_c', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memorias', models.ManyToManyField(to='pedidos.Memoria')),
                ('pl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.PlacaMae')),
                ('processador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.Processador')),
                ('vga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.Vga')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
                ('computadores', models.ManyToManyField(to='pedidos.Computador')),
            ],
        ),
    ]
