# Generated by Django 2.2.7 on 2019-11-24 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pedidos', '0007_auto_20191124_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='computador',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='computadores', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
