# Generated by Django 2.2.7 on 2019-11-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_computador_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computador',
            options={'verbose_name': 'computador', 'verbose_name_plural': 'computadores'},
        ),
        migrations.AlterField(
            model_name='processador',
            name='marca',
            field=models.CharField(max_length=20, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='processador',
            name='nome',
            field=models.CharField(choices=[('Intel Core i5', 'Intel Core i5'), ('Intel Core i7', 'Intel Core i7'), ('Amd Atlhon', 'AMD Athlon'), ('Amd Rysen7', 'AMD Rysen 7')], max_length=20, verbose_name='Nome'),
        ),
    ]
