# Generated by Django 2.2.7 on 2019-11-25 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_remove_processador_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placamae',
            name='nome',
            field=models.CharField(choices=[('Asus Prime', 'Asus Prime'), ('Gigabyte', 'Gigabyte'), ('AsRock Fatal', 'AsRock Fatal')], max_length=20, verbose_name='Nome Placa Mãe'),
        ),
        migrations.AlterField(
            model_name='vga',
            name='modelo',
            field=models.CharField(choices=[('Gigabyte Geforce Gtx 1060 6gb', 'Gigabyte Geforce GTX 1060 6GB'), ('pny_rtx_2060_6gb', 'PNY RTX 2060 6GB'), ('radeon_rx_580_8GB', 'Radeon RX 580 8GB')], max_length=50, verbose_name='Modelo'),
        ),
    ]
