# Generated by Django 2.2.7 on 2019-11-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0011_auto_20191124_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memoria',
            name='marca',
        ),
        migrations.AlterField(
            model_name='memoria',
            name='capacidade',
            field=models.CharField(choices=[(4, 4), (8, 8), (16, 16), (32, 32), (64, 64)], max_length=20, verbose_name='Capacidade'),
        ),
    ]
