# Generated by Django 2.2.7 on 2019-11-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0013_auto_20191125_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoria',
            name='capacidade',
            field=models.CharField(choices=[('4', '4'), ('8', '8'), ('16', '16'), ('32', '32'), ('64', '64')], max_length=20, verbose_name='Capacidade'),
        ),
    ]
