# Generated by Django 2.2.7 on 2019-11-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0014_auto_20191125_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computador',
            name='memorias',
            field=models.ManyToManyField(related_name='memorias', to='pedidos.Memoria'),
        ),
    ]
